import {
  KEY_ACCELERATE, PLAYER_ACCELERATE,
  KEY_DECELERATE, PLAYER_DECELERATE,
  KEY_ROTATE_CLOCKWISE, PLAYER_ROTATE_CLOCKWISE,
  KEY_ROTATE_ANTI_CLOCKWISE, PLAYER_ROTATE_ANTI_CLOCKWISE
  KEY_SHOOT, PLAYER_SHOOT
} from '../../common/constants';

export default {
  [KEY_ACCELERATE]: PLAYER_ACCELERATE,
  [KEY_DECELERATE]: PLAYER_DECELERATE,
  [KEY_ROTATE_CLOCKWISE]: PLAYER_ROTATE_CLOCKWISE,
  [KEY_ROTATE_ANTI_CLOCKWISE]: PLAYER_ROTATE_ANTI_CLOCKWISE,
  [KEY_SHOOT]: PLAYER_SHOOT
}

